image: hosttoday/ht-docker-node:npmts

stages:
- test
- release
- page

testLEGACY:
  stage: test
  script:
    - npmci test legacy
  tags:
    - docker

testLTS:
  stage: test
  script:
    - npmci test lts
  tags:
    - docker
    
testSTABLE:
  stage: test
  script:
    - npmci test stable
  tags:
    - docker

release:
  stage: release
  environment: npmjs-com_registry
  script:
    - npmci publish
  only:
    - tags
  tags:
    - docker

pages:
  image: hosttoday/ht-docker-node:npmpage
  stage: page
  script:
    - npmci command npmpage --host gitlab
  only:
    - tags
  artifacts:
    expire_in: 1 week
    paths:
    - public